			<div class="container">
        		<div class="row">
        			<div class="col">
        				<h3><?php echo $this->title; ?></h3>
        			</div>
        			<div class="d-flex justify-content-end">
        				<?php echo $this->formRow($form->get('SUBMIT')); ?>&nbsp;
        				<?php if (isset($this->uuid)) : ?>
        					<a href="<?=$this->url('dog/dog', ['action' => 'delete', 'uuid' => $this->uuid])?>" class="btn btn-danger">Delete</a>
        				<?php endif; ?>
        			</div>
        		</div>
        	</div>
			
			<!-- Hidden Elements -->
			<?php echo $this->form()->openTag($form); ?>
			<div class="form-group">
				<?php echo $this->formRow($form->get('SECURITY')); ?>
			</div>
			
			<div class="form-group">
				<?php echo $this->formRow($form->get('USERNAME')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('FNAME')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('LNAME')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('ADDR1')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('ADDR2')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('CITY')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('STATE')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('ZIP')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('PHONE')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('EMAIL')); ?>
			</div>
			<?php if (!$this->update) : ?>
			<div class="form-group">
				<?php echo $this->formRow($form->get('PASSWORD')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('CONFIRM_PASSWORD')); ?>
			</div>
			<?php endif; ?>
			<div class="form-group">
				<?php echo $this->formRow($form->get('SUBMIT')); ?>
			</div>
			<?php echo $this->form()->closeTag($form); ?>
