<div class="container">
	<div class="row">
		<div class="col-sm-6">
			<h3><?php echo $this->title; ?></h3>
			
			<!-- Hidden Elements -->
			<?php echo $this->form()->openTag($form); ?>
			<div class="form-group">
				<?php echo $this->formRow($form->get('SECURITY')); ?>
				<?php echo $this->formRow($form->get('UUID')); ?>
			</div>
			
			<div class="form-group">
				<?php echo $this->formRow($form->get('USERNAME')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('EMAIL')); ?>
			</div>
			<?php if (!$this->update) : ?>
			<div class="form-group">
				<?php echo $this->formRow($form->get('PASSWORD')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('CONFIRM_PASSWORD')); ?>
			</div>
			<?php endif; ?>
			<div class="form-group">
				<?php echo $this->formRow($form->get('STATUS')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('DATE_CREATED')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('DATE_MODIFIED')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('SUBMIT')); ?>
			</div>
			<?php echo $this->form()->closeTag($form); ?>
		</div>
	</div>
</div>